flatpak/xdg-dbus-proxy

- dbus-proxy.c
If it isn't told that usage() never returns, gcc 8 warns:
dbus-proxy.c: In function ‘parse_generic_args’:
dbus-proxy.c:215:1: warning: control reaches end of non-void function [-Wreturn-type]
> Reassure compiler that parse_generic_args() always returns a value

- backport-autoptr.h
- tests/test-proxy.c
Testing #5 on Travis-CI revealed some incompatibilities with older GLib and dbus versions:
* backport-autoptr.h declared autoptr cleanup for GSubprocess twice
* test-proxy.c didn't use backport-autoptr.h
* test-proxy.c gave dbus-daemon an option that was only introduced recently (and seems to be unnecessary here)
This pull request makes it work with GLib 2.40 on Ubuntu 14.04.
---
I'm happy to de-support older GLib releases as needed - Flatpak officially only supports GLib 2.44 and up, although I have patches that made Flatpak 1.0.x work on 2.42 and probably also 2.40.
We should probably test regularly on a distro that has the oldest GLib we support, for which see a subsequent pull request that adds Travis-CI integration.
> Improve compatibility with older OSs

- .travis.yml
- backport-autoptr.h
- tests/ci-Dockerfile.in
- tests/ci-build.sh
- tests/ci-install.sh
- tests/test-proxy.c
This complements #6 by adding test coverage on various distros of varying age, including Ubuntu 14.04 (GLib 2.40, which is the oldest we can reasonably support at the moment).
If the baseline distribution is meant to be newer than that, we can adjust the suites used: Debian releases and Ubuntu LTS releases are about a year apart, so we can easily hit about 50% of possible GLib branches.
The scripts in tests/ are reasonably CI-system-agnostic and should be feasible to hook up to Gitlab-CI or similar if desired (as has been done in dbus). It should also be reasonably straightforward to build
in a non-Debian-derived container by adding an alternative code path alongside the various apt-get calls.
If this is merged, contributors can enable Travis-CI for their forks even if it isn't enabled …
> Add Travis-CI integration, based on what I contributed to dbus

- flatpak-proxy.c
Per the docs on g_socket_listener_add_address(), setting error to NULL
causes the parameter to be ignored. If an error occurs in
flatpak_proxy_start(), start_proxy() will attempt to print
error->message where error is then NULL, causing a segfault.
So, don't set error to NULL.
Signed-off-by: Matt Merhar <mattmerhar@protonmail.com>
> Fix segfault when flatpak_proxy_start() fails

- .gitignore
- Makefile.am
- configure.ac
- m4/ax_ac_append_to_file.m4
- m4/ax_ac_print_to_file.m4
- m4/ax_add_am_macro_static.m4
- m4/ax_am_macros_static.m4
- m4/ax_code_coverage.m4
- m4/ax_file_escapes.m4
Similar to <https://gitlab.freedesktop.org/dbus/dbus/merge_requests/88> and <https://gitlab.freedesktop.org/dbus/dbus/merge_requests/86>.
---
build: Forbid AX_-prefixed patterns more selectively
We want to make autoconf fail early and with a user-comprehensible message if autoconf-archive isn't installed, rather than generating a configure script with syntax errors, or a configure script that runs successfully but doesn't do what we intended.
However, autoconf-archive doesn't actually guarantee not to use AX_-prefixed shell variable names without m4_pattern_allow'ing them (unlike Autoconf, Automake, Libtool and pkg-config, which explicitly use m4_pattern_allow for variables with AC_, AM_, LT_ and PKG_ prefixes), so it isn't safe to assume that they won't be used. In particular, according …
> Adapt to API change in autoconf-archive 2019.01.06

- dbus-proxy.c
Taken from https://github.com/void-linux/void-packages/blob/master/srcpkgs/xdg-dbus-proxy/patches/musl.patch .
> Fix musl compilation by adding TEMP_FAILURE_RETRY

- dbus-proxy.c
To enable locales. This fixes UTF-8 characters being converted to ?
characters when printing error messages with e.g. g_warning().
Note: this is not at all important or urgent or anything, just something that tripped me up when debugging today.
> Call setlocale()

- flatpak-proxy.c
Buffer contains a default size of data that is 16 bytes, so that  it can be used on the stack for reading the header. However we also support passing in sizes smaller that 16, which will allocate a smaller object than the full Buffer object. This is safe as we respect the size member, however there is no way for GCC to know this, so we silence it manually.
> Silence GCC warnings about size of Buffer

- .github/workflows/check.yml
This is based on the one from Flatpak, but doesn't include everything
that the Flatpak one does yet, because we can't usefully test a workflow
until a simple workflow is already in place.
Co-authored-by: Alexander Larsson <alexl@redhat.com>
Co-authored-by: Phaedrus Leeds <mwleeds@endlessos.org>
Signed-off-by: Simon McVittie <smcv@collabora.com>
> workflows: Add a Github CI workflow

- .github/workflows/check.yml
- Makefile.am
- meson.build
- meson_options.txt
- tests/Makefile.am.inc
- tests/meson.build
- tests/use-as-subproject/.gitignore
- tests/use-as-subproject/README
- tests/use-as-subproject/config.h
- tests/use-as-subproject/dummy-config.h.in
- tests/use-as-subproject/meson.build
This allows xdg-dbus-proxy to be built as a subproject in larger Meson
projects. When built as a subproject, we install into the --libexecdir
and require a program prefix to be specified: for example, Flatpak would
use program_prefix=flatpak- to get /usr/libexec/flatpak-dbus-proxy.
> Add a Meson build system

- .gitignore
- m4/ax_check_gnu_make.m4
- m4/ax_code_coverage.m4
ax_code_coverage.m4 needs ax_check_gnu_make.m4, so this fixes a build failure if autoconf-archive isn't installed.
I've also checked that all the other autoconf-archive-sourced files are up to date; ax_code_coverage.m4 was the only one that needed updating.
Fixes #17.
> Add missing ax_check_gnu_make.m4

- flatpak-proxy.c
If the reply to Hello() is an error (or some other non-reply), we don't
want to fall through to EXPECTED_REPLY_REWRITE. Treat it like
EXPECTED_REPLY_NORMAL instead.
---
Detected by enabling more warnings during #31.
> flatpak-proxy: Fix unintended fallthrough

- dbus-proxy.c
- flatpak-proxy.c
- meson.build
Includes #32, which is the only compiler warning that seemed like it indicated a genuine bug; please review that one first.
* #32
* dbus-proxy: Treat GPtrArray index as unsigned
This squashes some -Wsign-compare warnings.
* buffer_read: Be more careful with signedness
* flatpak-proxy: Silence compiler warnings about invalid casts
GSource and -Wcast-function-type don't really get on, but G_SOURCE_FUNC
has the appropriate magic to stop the compiler warning about this cast.
* flatpak-proxy: Move a case from an if() into a switch()
Instead of special-casing EXPECTED_REPLY_NONE to be a separate if()
block, treating it as part of the switch() lets us use -Wswitch-enum
to warn if we have missed one.
* flatpak-proxy: Handle every case in a switch
This lets us use -Wswitch-enum to detect when …
> Fix various compiler warnings

- meson.build
- meson_options.txt
When using xdg-dbus-proxy as a subproject in Flatpak, we don't
necessarily want to run its unit tests as part of Flatpak's test
suite.
In particular, when bundling selected source code from xdg-dbus-proxy
into Flatpak `make dist` tarballs, it would be simpler if we could
avoid having to include the unit tests.
> Add an option to disable build-time tests

- meson_options.txt
- tests/Makefile.am.inc
- tests/meson.build
- tests/tap.test.in
This is used in the Debian packaging via ginsttest-runner and the
autopkgtest framework. Previously, it was supported by the Autotools
build system but not by the Meson build system.
> meson: Optionally install tests for "as-installed" testing

- flatpak-proxy.c
According to the D-Bus specifications: https://dbus.freedesktop.org/doc/dbus-specification.html#id-1.4.4
> For the STRING and OBJECT_PATH types, [the data length] is encoded in 4 bytes (a UINT32).
But the code was trying to parse the 32-bit integer as an 8-bit one, meaning that, as was the case with object paths created by the dLeyna project, a 259-byte long string would be parsed like a 3-byte long one.
> flatpak-proxy: Fix D-Bus disconnection with overly long object paths

- flatpak-proxy.c
`Invalid message header format` was printed without more details. Printing where the invalid message header came from might help in debugging.
> flatpak-proxy: Tell where "Invalid message header format" comes from

- meson_options.txt
When using meson 1.2.1, `meson build` prints:
NOTICE: Future-deprecated features used:
* 1.1.0: {'"boolean option" keyword argument "value" of type str'}
This patch defines the default values for boolean fields using the native boolean type and squelches this warning.
> meson: update deprecated syntax

- flatpak-proxy.c
Based on a patch (https://github.com/flatpak/xdg-dbus-proxy/issues/51#issuecomment-2020464257) by @spiiroin with an extra commit on top fixing a few more cases.
> Fix a bunch of memory leaks

- flatpak-proxy.c
Separation between messages created by client and proxy was ensured by
requiring the client to use monotonically increasing serials and adding
an offset to distinguish the client message from proxy messages.
The requirement to only send messages with increasing serials cannot be
ensured by libraries godbus or zbus.
This commit instead reserves the lower_bit=0 space for client messages
and the lower_bit=1 for messages created by the proxy. This gets rid of
any serial translation mechanism and the requirement for increasing serials.
However, it limits the possible values of serials available to the client
to about half of the usual maximum value.
Closes #46
> Split proxy/client serials based on lower bit

- flatpak-proxy.c
The context is to allow for AT-SPI broadcast signals (specifically `EventListenerRegistered` and `EventListenerDeregistered` from the `org.a11y.atspi.Registry` interface on the registry object) to be allowed through, without giving apps a full talk permission to it.
CC @ebassi @smcv 
~@smcv I appreciate this goes directly against https://gitlab.freedesktop.org/dbus/dbus/-/issues/185#note_48128, but I don't understand that restriction and would appreciate some ellucidation as to why that's been proposed. I'm not particularly sold on this approach so any advice will be highly welcomed!~
Edit: see https://github.com/flatpak/xdg-dbus-proxy/pull/61#issuecomment-2134772967 for a more up-to-date understanding of the D-Bus issue.
> Don't require TALK permission for broadcast rules
